### ISSUE TITLE
I don't have the item

### ISSUE THREAD

**Issue by NepDisk** [SmartDEVTeam/Mob-Battle-Addon#1]
I'm playing on the Intel atom nuvison tm785m3 tablet it is not in the creative inventory

**Comment by ThePixelGamer** [comment]
@yoshikirby43 Is your device x86?

**Comment by ThePixelGamer** [comment]
@yoshikirby43 So I looked through google and yes, you do have a x86 processor. Could you DM me on twitter so we can talk easier. Twitter Name : @ThePixelCoder

**Comment by NepDisk** [comment]
@yoshikirbyGa1

**Comment by NepDisk** [comment]
Never mind my tweeter is not working just use hangsout to get to talk to me
